apiVersion: v2
name: immich
description: A Immich Helm chart targeted at advanced users
home: https://immich.app/
icon: https://raw.githubusercontent.com/immich-app/immich/main/design/immich-logo.svg
sources:
  - https://github.com/secustor/helm-charts/tree/main/charts/immich
  - https://github.com/immich-app/immich
maintainers:
  - name: secustor
    email: sebastian@poxhofer.at

type: application
version: 0.6.0
# renovate: image=ghcr.io/immich-app/immich-server
appVersion: "v1.133.1"

annotations:
  artifacthub.io/category: storage
  artifacthub.io/links: |
    - name: support
      url: https://github.com/secustor/helm-charts/issues
  artifacthub.io/changes: |
    - Break change: The `immich-server` image was updated to `v1.133.1` which contains breaking changes. If you are using `pgvector` you should be fine else you need to migrate your database. https://github.com/immich-app/immich/releases/tag/v1.133.0
