apiVersion: v2
name: immich
description: A Immich Helm chart targeted at advanced users
home: https://immich.app/
icon: https://raw.githubusercontent.com/immich-app/immich/main/design/immich-logo.svg
sources:
  - https://github.com/secustor/helm-charts/tree/main/charts/immich
  - https://github.com/immich-app/immich
maintainers:
  - name: secustor
    email: sebastian@poxhofer.at

type: application
version: 1.0.11
# renovate: image=ghcr.io/immich-app/immich-server
appVersion: "v2.5.2"

annotations:
  artifacthub.io/category: storage
